apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-front
  template:
    metadata:
      labels:
        app: app-front
    spec:
      containers:
      - name: app-front
        image: cruigo93/task2front
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: front
          containerPort: 8080
